// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZHofWgJB9vFuqScO-nm09xQeLxuQYxko',
    appId: '1:698490038984:web:4a4d1ba1ef56f35c3053fd',
    messagingSenderId: '698490038984',
    projectId: 'mizizi-learning',
    authDomain: 'mizizi-learning.firebaseapp.com',
    storageBucket: 'mizizi-learning.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2uQZKyjNj6Ru0SHjKugaCDyuSc6flJio',
    appId: '1:698490038984:android:8793306236611a963053fd',
    messagingSenderId: '698490038984',
    projectId: 'mizizi-learning',
    storageBucket: 'mizizi-learning.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6jIGqGm2omXbSS0x8Q3q36yF5DGl1oCk',
    appId: '1:698490038984:ios:d93c3f5a7699a0683053fd',
    messagingSenderId: '698490038984',
    projectId: 'mizizi-learning',
    storageBucket: 'mizizi-learning.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6jIGqGm2omXbSS0x8Q3q36yF5DGl1oCk',
    appId: '1:698490038984:ios:d93c3f5a7699a0683053fd',
    messagingSenderId: '698490038984',
    projectId: 'mizizi-learning',
    storageBucket: 'mizizi-learning.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZHofWgJB9vFuqScO-nm09xQeLxuQYxko',
    appId: '1:698490038984:web:3eea4c13403620813053fd',
    messagingSenderId: '698490038984',
    projectId: 'mizizi-learning',
    authDomain: 'mizizi-learning.firebaseapp.com',
    storageBucket: 'mizizi-learning.firebasestorage.app',
  );
}
